5/blog_on_rails/config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments, shallow: true, only: [:create, :destroy]
  end

  resources :users, only: [:new, :create]

  resource :sessions, only: [:new, :destroy, :create]

  root to: "posts#index"
end

5/blog_on_rails/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    # When defining permission with the `can` method inside
    # of the ability file, the arguments are:
    # - The first is a symbol that represents the action
    #   we're verifying permission for.
    #   (e.g. :create, :edit, :delete, like, :etc.)
    # - The second argument is the class of the objects
    #   we'll verifying permission with which are usually models.
    #   (e.g. Question, Answer, User, etc)
    # - The last is a block that must return a boolean. If true,
    #   the user has permission to perform the action the instance
    #   of the given class.
  
    can(:manage, Post) do |post|
      # |question| is the instance of the Question
      # Here we compare the `current_user` to the
      # the owner of the question. If they're the same,
      # the `current_user` is allowed to :manage the question.
      user == post.user
    end

    can(:manage, Comment) do |comment|
      user == comment.user
    end

    # Inside this file, Ability.rb, we define permission rules
    # with the `can` method.

    # Outside of this file, we use a completely different method
    # named `can?` to test the permission defined in this file.
    # (e.g. can the user "Jon" delete that answer -> can?(:delete, ))

  end
end

5/blog_on_rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

5/blog_on_rails/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  
  validates :body, presence: true

  belongs_to :post
end

5/blog_on_rails/app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :body, presence: true, length: { minimum: 50 }

  has_many :comments, dependent: :destroy

  belongs_to :user, optional: true
end

5/blog_on_rails/app/models/user.rb
class User < ApplicationRecord
  has_secure_password

end

5/blog_on_rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def authenticate_user!
    redirect_to new_session_path, notice: "Please sign in" unless user_signed_in?
  end

  def user_signed_in?
    current_user.present?
  end
  helper_method :user_signed_in?

  def current_user
    @current_user ||= User.find_by_id session[:user_id]
  end
  helper_method :current_user

end

5/blog_on_rails/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_comment
  before_action :find_post
  before_action :authorize_user!, only: [:destroy]

  def create
    @comment = Comment.new comment_params
    @comment.post = @post
    @comment.user = current_user

    if @comment.save
      flash[:success] = "Comment added!"
      redirect_to @post
    else
      @comments = @post.comments.order(created_at: :desc)
      flash.now[:alert] = @comment.errors.full_messages.join(", ")
      render "posts/show"
    end
  end

  def destroy
    @comment.destroy
    flash[:success] = "Comment deleted"
    redirect_to @comment.post
  end

  private
  def find_comment
    @comment = Comment.find params[:id] if params[:id].present?
  end

  def find_post
    @post = Post.find params[:post_id] if params[:post_id].present?
  end

  def comment_params
    params.require(:comment).permit(:body)
  end

  def authorize_user!
    unless can?(:manage, @comment)
      flash[:alert] = "Get outta here, sucka!"
      redirect_to post_path(@comment.post)
    end
  end

end

5/blog_on_rails/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize_user!, only: [:edit, :update, :destroy]

  def index
    @posts = Post.order(created_at: :desc)
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new post_params
    @post.user = current_user

    if @post.save
      flash[:success] = "Post created!"
      redirect_to @post
    else
      flash.now[:alert] = @post.errors.full_messages.join(", ")
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update post_params
      flash[:success] = "Post updated!"
      redirect_to @post
    else
      flash.now[:alert] = @post.errors.full_messages.join(", ")
      render :edit
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "Post deleted"
    redirect_to posts_path
  end

  private
  def find_post
    @post = Post.find(params[:id]) if params[:id].present?
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def authorize_user!
    unless can?(:manage, @post)
      flash[:alert] = "Beat it!"
      redirect_to post_path(@post)
    end
  end

end

5/blog_on_rails/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_email params[:email]
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Logged in"
    else
      flash[:alert] = "You messed up sucka"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged Out"
  end

end

5/blog_on_rails/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Logged In!"
    else
      render :new
    end
  end

  def update
    user.update(user_params)
  end

  private

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :email,
      :password
    )
  end
end

5/blog_on_rails/app/helpers/application_helper.rb
module ApplicationHelper
end

5/blog_on_rails/app/helpers/sessions_helper.rb
module SessionsHelper
end

5/blog_on_rails/app/helpers/users_helper.rb
module UsersHelper
end

5/blog_on_rails/app/views/comments/_form.html.erb
<%= form_for [@post, @comment] do |f| %>
  <div class="form-group">
    <%= f.text_area :body, placeholder: "What's on your mind?", class: "form-control" %>
  </div>

  <%= f.submit "Submit", class: "btn btn-outline-primary" %>
<% end %>

5/blog_on_rails/app/views/comments/edit.html.erb
<%= render 'form' %>

5/blog_on_rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogOnRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand sticky-top navbar-outline-primary bg-light mb-4">
      <%= link_to "Blog On Rails", root_path, class: "navbar-brand" %>

      <div class="collapse navbar-collapse">
        <div class="navbar-nav ml-auto">
          <%= link_to "Home", root_path, class: "nav-item nav-link" %>
          <% if user_signed_in? %>
      <div class= "nav-item nav-link">Hello, <%= current_user.first_name %>!</div>
      
      <%= link_to 'Sign Out', sessions_path, method: :delete, class: "nav-item nav-link" %>
    <% else %>
          <%= link_to "Login", new_sessions_path, class: "nav-item nav-link" %>
          <%= link_to "Sign Up", new_user_path, class: "nav-item nav-link" %>
      
    <% end %>
          <%= link_to "New Post", new_post_path, class: "nav-item nav-link" %>
        </div>
      </div>
    </nav>


    <div class="container-fluid">
      <% flash.each do |type, message| %>
        <div class="alert alert-<%= type == "alert" ? "danger" : "success" %>" role="alert">
          <%= message %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

5/blog_on_rails/app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control" %>
  </div>

  <%= f.submit class: "btn btn-outline-primary" %>
<% end %>

5/blog_on_rails/app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

5/blog_on_rails/app/views/posts/delete.html.erb
<h1>Posts#delete</h1>
<p>Find me in app/views/posts/delete.html.erb</p>

5/blog_on_rails/app/views/posts/edit.html.erb
<%= render 'form' %>

5/blog_on_rails/app/views/posts/index.html.erb
<div class="row">
  <% @posts.each do |post| %>
    <div class="col-sm-6 col-lg-4">
      <div class="card mb-4">
        <div class="card-body">
          <h5 class="card-title text-truncate"><%= link_to post.title, post_path(post) %></h5>
          <p class="card-text text-truncate"><%= post.body %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

5/blog_on_rails/app/views/posts/new.html.erb
<%= form_for @post do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control" %>
  </div>

  <%= f.submit class: "btn btn-outline-primary" %>
<% end %>

5/blog_on_rails/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p><%= @post.body %></p>

<p><small>Posted <%= time_ago_in_words @post.created_at %> ago</small></p>

<div class="owner-controls mb-4">
  <%= link_to "Edit", edit_post_path(@post), class: "btn btn-outline-primary" %>
  <%= link_to "Delete", post_path(@post), method: :delete, class: "btn btn-outline-primary" %>
</div>

<h4>Comment</h4>

<%= render 'comments/form' %>

<ul class="list-unstyled mt-4">
  <% @comments.each do |comment| %>
    <li class="media mb-2">
      <div class="media-body">
        <%= comment.body %> <br/>
        <small>
          Commented <%= time_ago_in_words comment.created_at %> ago •
          <%= link_to 'Delete', comment_path(comment), method: :delete %>
        </small>
    </li>
  <% end %>
</ul>

5/blog_on_rails/app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

5/blog_on_rails/app/views/users/new.html.erb
<!-- app/views/users/new.html.erb -->
<h1>Sign Up</h1>

<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name%>
  </div>
  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit %>
  <% end %>

5/blog_on_rails/app/views/users/update.html.erb
<h1>Update</h1>

<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name%>
  </div>
  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit %>
  <% end %>